### ISSUE TITLE
High-Res Earth Clouds misaligned

### ISSUE THREAD

**Issue by DegenerateGroundState** [PhineasFreak/RSSVE#14]
KSP Version **1.3.1.1891 Win x64 en-us**
Scatterer **0.0324**
EVE **1.2.2.1**
RSSVE **master**
RSS **v13.0**
RSS textures **4096x2048 v13.1**

1. I downloaded the master branch as a zip.
2. I extracted the main RSSVE folder to gamedata.
3. I extracted the RSSVE folder from RSSVE_extras into gamedata overwriting all files with the same name.
4. Then I loaded a save and viewed Earth from the tracking station and map view in a mission:

[Tracking Station](https://i.imgur.com/nvFhs0C.png)
[Map View](https://i.imgur.com/sqOfK10.png)
RSSVE master looks normal if I don't extract the high-res pack on top of it.

<details>
<summary>Other mods:</summary>
RN-USRockets ConnectedLivingSpace DeadlyReentry HangerExtenderExtended KSP-AVC MechJeb2 ProceduralFairings ProceduralParts PersistentRotation RCSBuildAidCont KSCSwitcher RN-USProbesPack RemoteTech TACLS TextureReplacerReplaced Toolbar VenStockRevamp DMagicOrbitalScience KAS SCANsat ATKPropulsionPack CryoEngines FASA FilterExtensions NearFutureConstruction NearFuturePropulsion NearFutureSolar NearFutureSpacecraft RLARecontinued SovietEnginePack RealScaleBoosters RN-SalyutStations RN-SovietRockets RN-Skylab RN-SovietProbes RealismOverhaulCraftFiles RealismOverhaul RocketdyneF-1 SXTContinued Taerobee NewTantares
NewTantaresLV RealEngines UniversalStorage AdvancedJetEngine FerramAerospaceResearch ModuleManager ModularFlightIntegrator SolverEngines KerbalJointReinforcement RealChute RealFuels CommunityResourcePack RealHeat
RealPlume SmokeScreen BackgroundResources ASETAgency B9PartSwitch CryoTanks DynamicBatteryStorage DeployableEngines NearFutureSolar-Core NearFutureProps BDAnimationModules FirespitterCore FirespitterResourcesConfig RetractableLiftingSurface AGExt AviationLights DangerAlertsContinued DecalStickers MemGraph DistantObject DistantObject-RealSolarSystem DockingPortAlignmentIndicator EditorExtensionsRedux EngineLighting EVAParachutes ExceptionDetector FreedomTex HazardTanksTextures HullcamVDSContinued JanitorsCloset KerbalAlarmClock KerbalFlightData KerbalHotSeatCont KIS KramaxAutopilotContinued MainSailorTextures-Complete NEBULADecalsContinued PoodsMilkyWaySkybox ProceduralParts-Textures-SaturnNova ProceduralParts-Textures-SCCKSCS RasterPropMonitor TrimIndicator RSSDateTimeFormatter CustomAsteroids Scatterer-config Scatterer-sunflare SmartParts KerbalConstructionTime VaporVent VensStylePPTextures TriggerAu-Flags CommunityCategoryKit TweakScale ClickThroughBlocker ASETProps RasterPropMonitor-Core JSIPartUtilities MainSailorTextures-Essentials SigmaReplacements-SkyBox Kopernicus MagiCore TexturesUnlimited ContractConfigurator CustomBarnKit WaypointManager StageRecovery DecouplerShroud AnimatedDecouplers xScience KRASH RP-1-dev TestFlight Principia</details>

**Comment by DegenerateGroundState** [comment]
[output_log.txt](https://github.com/PhineasFreak/RSSVE/files/2019896/output_log.txt)

**Comment by PhineasFreak** [comment]
Hmm, the cubemap faces/texture paths are probably flipped. Let me check it and i will report back.

**Comment by PhineasFreak** [comment]
OK, the latest patch fixes that. I just messed up when uploading the files (uploaded a "dds-ified" testing version of the .png cubemap instead of the proper .dds cubemap - KSP .dds textures need to be flipped vertically when converting them from other image formats but i forgot to do so).

Please test and report back.

**Comment by DegenerateGroundState** [comment]
Looks good!
[Tracking Station](https://i.imgur.com/zzRj4IF.png)
[Mission Map view zoomed in](https://i.imgur.com/kDht3s3.png)
[Mission map view zoomed out](https://i.imgur.com/ep2ohX3.png)

**Comment by PhineasFreak** [comment]
Yes, [the source texture itself is 32K](http://www.celestiamotherlode.net/catalog/show_addon_details.php?addon_id=406). I also wanted to keep it compatible with most systems, since under DirectX 9.0/OpenGL 3.0 8K per side (4 sides total - 32K) is the maximum possible resolution.

I could upscale the texture to 16K per side (64K total) but a) upscaling is "meh" and b) will then **require** DX11/OpenGL 4.0. It may be a moot point though since the minimum hardware requirements by the basic RSSVE package also covers these anyway (all GFX cards since 2008/2009 support DX11/OGL 4.0).

**Comment by DegenerateGroundState** [comment]
Well, since the clouds aren't meant to realistically depict the real clouds of whatever day you're playing, up-scaling could be good if it were to use some cloud-like detail generating algorithm. I recall seeing an algorithm like that over on the KSP forums. This could be getting out of scope, though.

**Comment by DegenerateGroundState** [comment]
I found the source of the source texture here: https://visibleearth.nasa.gov/view.php?id=57747 
It is 21.6k per hemisphere. Is that 43.2k when put together?

**Comment by DegenerateGroundState** [comment]
According to https://ladsweb.modaps.eosdis.nasa.gov/api/v1/productPage/product=MOD35_L2 the source (of the source of the source) cloud masks have a 250 meter resolution, which if I calculated it correctly should give a 1400k image (assuming it is square, and of the whole globe)
Earth surface area ~ <a href="https://www.codecogs.com/eqnedit.php?latex=510,000,000&space;km^{2}&space;=&space;5.1*10^{14}&space;m^{2}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?510,000,000&space;km^{2}&space;=&space;5.1*10^{14}&space;m^{2}" title="510,000,000 km^{2} = 5.1*10^{14} m^{2}" /></a>
<a href="https://www.codecogs.com/eqnedit.php?latex=\frac{5.1*10^{14}&space;m^{2}}{250&space;m^2}&space;=&space;2.04*10^{12}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\frac{5.1*10^{14}&space;m^{2}}{250&space;m^2}&space;=&space;2.04*10^{12}" title="\frac{5.1*10^{14} m^{2}}{250 m^2} = 2.04*10^{12}" /></a>total pixels

<a href="https://www.codecogs.com/eqnedit.php?latex=\sqrt{2.04*10^{12}}\approx&space;1,430,000" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\sqrt{2.04*10^{12}}\approx&space;1,430,000" title="\sqrt{2.04*10^{12}}\approx 1,430,000" /></a> pixels per side

**Comment by PhineasFreak** [comment]
I agree, the original texture does come from NASA Visible Earth. Unfortunately, the West and East parts are not aligned, even though they are supposed to be the two parts of the cloud atlas texture. The person who uploaded the Level 5 textures on The Celestia Motherlode merged these two parts to make them seamless.

The source texture is also not a power of two and the closest value for that is 32K, otherwise you have to upscale it to 64K. And downscaling is always better than upscaling, assuming that you do not "fill the blanks" with procedural particles as you mentioned.

And another thing: you have to consider that not everyone can load these textures. For example. a complete 64K atlas would require at least 5 GiB of VRAM (excluding the VRAM requested by other KSP operations). This is something that i cannot test as i do not have the required hardware in hand.

**Comment by DegenerateGroundState** [comment]
Closed, since the actual issue is fixed
