### ISSUE TITLE
water in map view

### ISSUE THREAD

**Issue by the-blue22** [PhineasFreak/RSSVE#16]
getting flashes of water in map view. we should have listened to al gore dammit ![how](https://user-images.githubusercontent.com/42012812/43551157-ec0676c0-95dd-11e8-853e-1b4f05b078f6.png)

**Comment by PhineasFreak** [comment]
Well, that's another Scatterer bug that i have not documented in the known issues. Did you by any chance reload your save while in-flight?

**PSA: Everyone, remember that Scatterer is still in the Alpha release cycle (v0.0XXX versioning). Expect major bugs (graphical or otherwise) that i have absolutely no control over them.**
