### ISSUE TITLE
Saturn atmosphere config not accounting for the bulge of the planet

### ISSUE THREAD

**Issue by francoiswnel** [PhineasFreak/RSSVE#2]
Just installed RSSVE as it's a better alternative than RVE at the moment. However, Saturn's atmosphere config appears to be completely circular, while the planet itself bulges out, which leaves a halo around the poles. Not sure if it's an issue on my setup or with the mod.

![screenshot9](https://cloud.githubusercontent.com/assets/7825549/18928880/5a06f560-85c2-11e6-8ee7-d0cc91f72a57.png)

**Comment by PhineasFreak** [comment]
No, the latest version of RSS enables the "Oblate" feature on the outer (gas) planets. At least for Jupiter and Saturn i have "fixed" (read: removed) this so that EVE and Scatterer can work correctly.

Can you confirm that this issue is also present at Jupiter? I use similar configs for both of them so i might have borked something accidentally for the Saturn one.

**Comment by francoiswnel** [comment]
Jupiter's atmosphere layer appears to be fine, and the planet seems to be bulging too.

![screenshot17](https://cloud.githubusercontent.com/assets/7825549/18951224/54aa75f6-8644-11e6-98bd-97f4c06a5d5b.png)

While going back to check it now, I noticed something odd going on at intermediate distance from Jupiter. Up close it's fine, and further away it's fine.

![screenshot18](https://cloud.githubusercontent.com/assets/7825549/18951283/a2396b92-8644-11e6-97dc-1f6f0c2a04c6.png)

**Comment by PhineasFreak** [comment]
Then i must have not done something correctly! I will investigate it and report back. Also, if you can please send me both your ModuleManager.ConfigCache and your KSP/Player.log files so that i can check whether the patches work (or not...)

I am well aware about the Z fighting of the Jupiter layers and i have some ideas of how to either mitigate or fix it. I remember it being OK but something about either EVE or Scatterer must have changed that.

**Comment by francoiswnel** [comment]
I don't have either of those files available. No ModuleManager.ConfigCache in my GameData directory, nor a Player.log in my KSP directory. Only found ModuleManager.Physics and ModuleManager.TechTree. Can I generate the other files?

Also noticed the Z fighting on Uranus, though it's much less apparent.

**Comment by PhineasFreak** [comment]
Hmmm, that is really weird! At least the KSP.log should exist as it is generated on every launch regardless of any installed mods.

Uranus and the other outer gas planets do not currently have either EVE or Scatterer configs so i do not know about it. It should be completely "stock", as provided by RSS itself,

**Comment by francoiswnel** [comment]
Ah, thought you meant KSP/ directory, not KSP or Player.log. I have a KSP.log file, it's 12 MB. How should I send it to you without making it public? Had a quick look, not sure if there's any personal information logged.

**Comment by PhineasFreak** [comment]
Wait a sec, i managed to reproduce the problem and i think i know what the problem is. That's why you always have to check everything two times...

**Comment by PhineasFreak** [comment]
@francoiswnel OK, the latest (24) patch fixes the issue. Please note that you have to clear the Kopernicus caches in order for the .bin files to be correct.

**Comment by francoiswnel** [comment]
Great stuff! Already downloading the latest files. Will let you know if there are any issues, probably tomorrow only though. Do I need to delete anything regarding Uranus?

**Comment by PhineasFreak** [comment]
No. If you want you can replace the Scatterer "PlanetsList.cfg" to remove the reference to Uranus (textures will be left untouched but the scatter effect will be disabled).

Speaking about the Z fighting it seems like it is caused only by Scatterer so i will experiment a bit in the following days to try and improve/fix it.

**Comment by francoiswnel** [comment]
Thanks. Just copied over the new files. Will test the config tomorrow.

**Comment by PhineasFreak** [comment]
Please do and report back! All testing is done by myself so a lot of things can be either be missed, be misconfigured or not work at all.

**Comment by PhineasFreak** [comment]
Small update: i have probably also fixed the Jupiter Z-fighting.

**Comment by francoiswnel** [comment]
Finally got around to KSP again, had a busy few days. Sorry for not testing sooner. Good news is that Saturn's atmosphere is fixed, and I don't notice any Z fighting at Jupiter. Bad news is that Earth's clouds are gone, cloud textures are gone and the city textures are gone. I'm also getting severe Z-fighting on the ocean surface. And my custom astroniki scatterer solar flare is not showing.

![screenshot19](https://cloud.githubusercontent.com/assets/7825549/19070737/0d8edc42-8a2d-11e6-8098-c2332f7c8ab9.png)

To install - I used CKAN to uninstall scatterer, then manually deleted the remaining scatterer directory, then used CKAN to reinstall scatterer. Then I deleted the RSSVE directory, and copied over the latest files from this repo, which only included the RSSVE and DistantObjects directories. I am assuming that you're loading the scatterer configs entirly using ModuleManager? I also deleted the Kopernicus caches. Did I miss anything? Relaunching KSP now to double check if there was any initialisation issues, but it takes a good 10 minutes to launch.

**Comment by PhineasFreak** [comment]
Since every EVE feature is misisng then i can safely assume that something about the whole EVE package is broken. Did you check if you have something like RSSVE/RSSVE/etc? For the record, i am going to move the Distant Object configs to be part of RSSVE itself (no more extra folders to make installation easier).

Yes, i converted the Scatterer configs to use MM to load so something might be broken for now.

For the custom flares, it is my "fault" since i am removing via MM any other sun flare config for now. This will be improved of course as i want my users to have full control over their preferences.

Ocean Z-fighting: if you open the Scatterer UI while in the main menu what is the value for the Near Clip camera?

**Comment by francoiswnel** [comment]
The install looks good to me. EnvironmentalVisualEffects contains two directories for plugins and shaders. RSSVE does not contain any subdirectory called RSSVE, it's just five directories and a couple of config files. Scatterer contains the vanilla scatterer files with the custom flare, both installed by CKAN. So not sure where it could be broken. Any ideas? Any info or files I can send you?

No problem regarding the flare, figured it might be something like that.

Will check that Near Clip value and update this comment.

**Comment by PhineasFreak** [comment]
Hmm, i did not touch the cloud configs at all for the latest patch...let me see if something was bocked during the transition.

**Comment by francoiswnel** [comment]
Unless I'm blind, I'm not seeing the Near Clip value. Are you referring to the load distance?

![screenshot20](https://cloud.githubusercontent.com/assets/7825549/19071876/9097b0fa-8a32-11e6-865f-adf3d2fc9e90.png)

**Comment by PhineasFreak** [comment]
No, you will find it in the main menu (before loading a save).

**Comment by francoiswnel** [comment]
Ah, I do have AutoLoadGame installed. Will disable that and check again. Perhaps that could be part of the issue. Will report back.

**Comment by PhineasFreak** [comment]
Meanwhile i am creating a new and clean installation to see if i missed anything.

**Comment by francoiswnel** [comment]
Man, I'm so sorry. It was totally my fault. As soon as I remembered I had AutoLoadGame installed, I also realised that I configured it to load my main save right when we last spoke - i.e. I had not played KSP since configuring AutoLoadGame. And guess what? Everything's working perfectly now that I've launched the game to the main menu, and then loaded a save.

I double checked Jupiter and Saturn again, all good there.

Sorry for the effort!

**Comment by PhineasFreak** [comment]
No problem, it is good to test the releases in situations that cannot be foreseen! I will add a note for users that have this mod installed.

**Comment by francoiswnel** [comment]
Good idea. I guess we learn things the hard way. Sorry again, and thanks for the great support - I know you're mainly making this mod for yourself so thanks. Give me a shout if you need any other tests done.

**Comment by PhineasFreak** [comment]
Thank you for your offer, i really appreciate it!

**Comment by PhineasFreak** [comment]
Small update for the custom sun flare problem: CKAN installs the Astroniki Sun flare at the wrong folder. That is normal since they had not a chance to update the NetKAN instructions to point it at the new location. But i made some minor changes to be 100% sure that all Scatterer Sun flares can work flawlessly.

**Comment by francoiswnel** [comment]
Okay, I've installed the latest patch, and I'm still seeing your sun flare config. CKAN installed the Astroniki flare into scatterer/sunflare. Is there anything I need to change to test your latest update?

**Comment by PhineasFreak** [comment]
To install the Astroniki sun flare correctly you need to:

* Move the textures that reside under scatterer/sunflare to scatterer/config/Sunflares/Sun
* Rename the sunflare.cfg to Sun.cfg and move it to scatterer/config/Sunflares

Correct, the green textures are the auroras. Currently they are a bit broken since EVE does not allow them to glow in the dark like some older versions but the 1.2 pre-release build has fixed that.

**Comment by francoiswnel** [comment]
Okay, so I followed your steps and moved the Astroniki flare files, but this is what the in game flare looks like right now:

![screenshot23](https://cloud.githubusercontent.com/assets/7825549/19123747/215d15d2-8b30-11e6-8b95-99ee0950a5ef.png)

I uninstalled and reinstalled scatterer and reapplied the same steps to make sure I did it correctly.

I am having some other issues now, I am not sure if it's related, but I didn't change anything else - only changed the scatterer files. The atmosphere is now taking on a peach tone, both from map view and in the space centre view.

![screenshot25](https://cloud.githubusercontent.com/assets/7825549/19123795/6c791c6e-8b30-11e6-9052-5873063d996e.png)

I am also getting insane slow down to 1 fps in the tracking centre, and I suspect it's because every station is trying to track my lone satellite. Possibly a bug with RemoteTech, although it was working fine this morning. I'll try and trouble shoot it later or tomorrow and get back to you if I discover something.

![screenshot24](https://cloud.githubusercontent.com/assets/7825549/19123828/af3d81b6-8b30-11e6-9fd9-d76e9a9afb9d.png)

**Comment by PhineasFreak** [comment]
OK, disregard the steps about the sun flare since the config structure has been changed for the new Scatterer release. None of the flares (apart from the one shipped with Scatterer) will work, you have to wait until they are updated by their respective modders.

By changing the Scatterer files, what do you mean?

**Comment by francoiswnel** [comment]
Right, I will reinstall scatterer with the default flare. Just meant moving the files as you instructed.

**Comment by PhineasFreak** [comment]
Oh, OK then!
