### ISSUE TITLE
Scatterer issue in 1.3.1

### ISSUE THREAD

**Issue by ajs117** [PhineasFreak/RSSVE#20]
Clean install of KSP v1.3.1

Installed RSS (with 8k textures) with CKAN
Installed RSS Visual Enhacements - High Resolution with CKAN

![image](https://user-images.githubusercontent.com/34308197/49036779-7f796380-f1b0-11e8-8a87-f9363fff6216.png)
[output_log.txt](https://github.com/PhineasFreak/RSSVE/files/2617017/output_log.txt)

**Comment by PhineasFreak** [comment]
Seems like the latest CKAN metadata update did not fix anything...oh well...

I would suggest to install RSSVE manually for now, you can find the installation instructions **[here](https://github.com/PhineasFreak/RSSVE/wiki/Installation)**.

**Comment by Growflavor** [comment]
@ajs117 With CKAN I often need to 'apply' scatterer after everything else is loaded in to GameData by CKAN otherwise it actually often does not install...especially with SVE and other visual mods not just RSSVE.  if 'applying' scatterer in CKAN by itself after everything else is already applied still fails, then I just manually drop it into game data.  I use version [0.0331b ](https://github.com/LGhassen/Scatterer/releases) with 1.3.1 ...here are some pretty videos just made in 1.3.1 using RSSVE v.1.3.1-5 (Thanks @PhineasFreak for this beautiful mod!) : 

[https://youtu.be/Ou9xjuPcxWc](url)

[https://youtu.be/5tRtvVh7pqM](url)

**Comment by PhineasFreak** [comment]
I think that the latest CKAN metadata updates changed the behavior to **not** include the default Scatterer configuration files for the celestial bodies/sun flares. Which is wrong since i depend on them (RSSVE is patching these via ModuleManager and only if they already exist in the GameData directory). That change would most probably have the results that the screenshot indicates.

@Growflavor And these pretty much are the reasons why i am not bothering with CKAN...

You have some really nice videos there! I really hope that eclipses will be improved some day so that they will blacken the complete sky and not just a part of it.

**Comment by DrRaphello** [comment]
My last attempt at fixing CKAN installation was on Dec 12th [link](https://github.com/KSP-CKAN/NetKAN/pull/6885) 
It works for me even if it is not fully correct. If anyone sees issues with it then please report them here.
