### ISSUE TITLE
Dev Branch | Scatterer configs

### ISSUE THREAD

**Issue by Theysen** [PhineasFreak/RSSVE#5]
Would you have ANY idea why the atmosphere effects vanish between 180.000m and 550.000m?! I am seriously out of ideas why this is happening and what to do to fix this. It must have to do with the newest scatterer but what exactly is causing this - no idea.

**Comment by PhineasFreak** [comment]
For every body? That's a new one but i already had serious problems with new Scatterer release so anything can be wrong.

**Comment by Theysen** [comment]
Please test it yourself with just the dev branch. It's specifically this band of altitude. If I don't find anything I will ask blackrack directly since it's not a config issue in the first place I assume

**Comment by PhineasFreak** [comment]
I will do but it can be anything (my own Scatterer textures, the Scatterer update, some kind of global config error that i introduced while testing). 

If you use the previous Scatterer .half textures but with the new configs do you get the same result?

**Comment by Theysen** [comment]
Oh, I didn't know you created new .half files. 

I can test it, but the configs were especially for the .halfs I PRed back then.

**Comment by PhineasFreak** [comment]
I remade them on the basis that we talked in the forum thread (Rt equal to atmosphere height, Rl equal to Rt + 1000). The result was really nice...for the bodies that i managed to get done.

At this point, i will not consider releasing another RC though. I cannot get the bodies to look how i want them to look and i am spending more time that i should trying to fix it. So. take your time.

**Comment by Theysen** [comment]
PhineasFreak, alright but that was basically completely the same what I had exported 😄 

I will test it over the weekend again if my old ones have the same issue, if not I will add the new scatterer config entries for clouds etc. And I will submit my Mars configs as well. Then going for the rest, if you instruct me what is still not working / looking off tell me and I try as well :) 

No worries, you have done so much already.

**Comment by PhineasFreak** [comment]
Well, you can say that i "double-checked"! Besides, only Earth and Mars were using the new convention.

It seems like there are some unexpected problems with the new Scatterer release, as Galileo has similar issues with SVE. Let's see if another release will fix or add a way to fix these.

**Comment by Theysen** [comment]
Am I correct your Master branch is compatible to 1.2.2? Because I just dropped that in and the LEO issue is gone. Everything looks gorgeous :) May I suggest though you lower the rim power of the uppermost config for 160000 to a value about 0.02 lower than the orbit exposure? It looks overbright at the moment and experimenting with them many times I think this is the sweet point for transition. More of what I did when I PR'd my configs for 1.1.3. Maybe you consider it :)

**Comment by PhineasFreak** [comment]
Everything should be working with the latest Scatterer release, although i have disabled the cloud integration for now (too buggy, cannot get the looks that i want).

The configs are all over the place since i was testing various things for the new Scatterer release. On top of that i was testing a program to automate the config point creation but i am not so sure if i like the results (they are more in-line with the altitude-pressure curve though).

I will make sure that the flight and map view parameters are the same though, since i will have to port your values back. Also, if you can/want, do an overall testing to check if i missed something.

**Off-topic:** One thing that i noticed was a persistent dark blue horizon but after setting the "skyExtinctionMultiplier" to be higher than 0 i got a smooth transition between the sky and the horizon.

**Comment by PhineasFreak** [comment]
@Theysen I push a new pre-release to stop people who cannot read from bugging Blackrack.
